name: share_handler_windows
description: An implementation for the Windows platform of the Flutter share_handler plugin.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  share_handler_platform_interface:
    path: ../share_handler_platform_interface

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: ShareHandlerWindowsPlatform
